name: Trigger Generate Website

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      target_service:
        description: 'Language-Technology-Assessment/website'
        required: true
      target_version:
        description: 'v1.0.0'
        required: true

permissions:
  actions: read
  id-token: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Language-Technology-Assessment/website
        run: |
          # Set the required variables
          repo_owner="Language-Technology-Assessment" 
          repo_name="European-open-ai-index"  
          event_type="trigger-workflow" 
          service="${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/nuxtjs.yml/dispatches \
            -d '{"ref":"main","inputs":{"service":"$service","version":"$version"}}'